//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1CUpdatesDownloader.UpdatePlatformReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://platform.api.update.company1c.com", ConfigurationName="UpdatePlatformReference.UpdatePlatformApi")]
    public interface UpdatePlatformApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="platformUpdateResult")]
        _1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateResult getPlatformUpdate(_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateRequest platformUpdateRequest);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BegingetPlatformUpdate(_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateRequest platformUpdateRequest, System.AsyncCallback callback, object asyncState);
        
        [return: System.ServiceModel.MessageParameterAttribute(Name="platformUpdateResult")]
        _1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateResult EndgetPlatformUpdate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="platformUpdateInfoResult")]
        _1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoResult getPlatformUpdateInfo(_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoRequest platformUpdateInfoRequest);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BegingetPlatformUpdateInfo(_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoRequest platformUpdateInfoRequest, System.AsyncCallback callback, object asyncState);
        
        [return: System.ServiceModel.MessageParameterAttribute(Name="platformUpdateInfoResult")]
        _1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoResult EndgetPlatformUpdateInfo(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://platform.api.update.company1c.com")]
    public partial class PlatformUpdateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MapElements[] additionalParametersField;
        
        private string loginField;
        
        private string passwordField;
        
        private string distributionUinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additionalParameters", Order=0)]
        public MapElements[] additionalParameters {
            get {
                return this.additionalParametersField;
            }
            set {
                this.additionalParametersField = value;
                this.RaisePropertyChanged("additionalParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string distributionUin {
            get {
                return this.distributionUinField;
            }
            set {
                this.distributionUinField = value;
                this.RaisePropertyChanged("distributionUin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://platform.api.update.company1c.com")]
    public partial class MapElements : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://platform.api.update.company1c.com")]
    public partial class PlatformUpdateInfoResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        private MapElements[] additionalParametersField;
        
        private string errorNameField;
        
        private string platformVersionField;
        
        private string transitionInfoUrlField;
        
        private string distributionUinField;
        
        private long sizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additionalParameters", Order=1)]
        public MapElements[] additionalParameters {
            get {
                return this.additionalParametersField;
            }
            set {
                this.additionalParametersField = value;
                this.RaisePropertyChanged("additionalParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string errorName {
            get {
                return this.errorNameField;
            }
            set {
                this.errorNameField = value;
                this.RaisePropertyChanged("errorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string platformVersion {
            get {
                return this.platformVersionField;
            }
            set {
                this.platformVersionField = value;
                this.RaisePropertyChanged("platformVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transitionInfoUrl {
            get {
                return this.transitionInfoUrlField;
            }
            set {
                this.transitionInfoUrlField = value;
                this.RaisePropertyChanged("transitionInfoUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string distributionUin {
            get {
                return this.distributionUinField;
            }
            set {
                this.distributionUinField = value;
                this.RaisePropertyChanged("distributionUin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("size");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://platform.api.update.company1c.com")]
    public partial class PlatformUpdateInfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MapElements[] additionalParametersField;
        
        private string configurationNameField;
        
        private string versionNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additionalParameters", Order=0)]
        public MapElements[] additionalParameters {
            get {
                return this.additionalParametersField;
            }
            set {
                this.additionalParametersField = value;
                this.RaisePropertyChanged("additionalParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string configurationName {
            get {
                return this.configurationNameField;
            }
            set {
                this.configurationNameField = value;
                this.RaisePropertyChanged("configurationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string versionNumber {
            get {
                return this.versionNumberField;
            }
            set {
                this.versionNumberField = value;
                this.RaisePropertyChanged("versionNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://platform.api.update.company1c.com")]
    public partial class PlatformUpdateResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        private MapElements[] additionalParametersField;
        
        private string errorNameField;
        
        private string downloadUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additionalParameters", Order=1)]
        public MapElements[] additionalParameters {
            get {
                return this.additionalParametersField;
            }
            set {
                this.additionalParametersField = value;
                this.RaisePropertyChanged("additionalParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string errorName {
            get {
                return this.errorNameField;
            }
            set {
                this.errorNameField = value;
                this.RaisePropertyChanged("errorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string downloadUrl {
            get {
                return this.downloadUrlField;
            }
            set {
                this.downloadUrlField = value;
                this.RaisePropertyChanged("downloadUrl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UpdatePlatformApiChannel : _1CUpdatesDownloader.UpdatePlatformReference.UpdatePlatformApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getPlatformUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getPlatformUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public _1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getPlatformUpdateInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getPlatformUpdateInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public _1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdatePlatformApiClient : System.ServiceModel.ClientBase<_1CUpdatesDownloader.UpdatePlatformReference.UpdatePlatformApi>, _1CUpdatesDownloader.UpdatePlatformReference.UpdatePlatformApi {
        
        private BeginOperationDelegate onBegingetPlatformUpdateDelegate;
        
        private EndOperationDelegate onEndgetPlatformUpdateDelegate;
        
        private System.Threading.SendOrPostCallback ongetPlatformUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBegingetPlatformUpdateInfoDelegate;
        
        private EndOperationDelegate onEndgetPlatformUpdateInfoDelegate;
        
        private System.Threading.SendOrPostCallback ongetPlatformUpdateInfoCompletedDelegate;
        
        public UpdatePlatformApiClient() {
        }
        
        public UpdatePlatformApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdatePlatformApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdatePlatformApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdatePlatformApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<getPlatformUpdateCompletedEventArgs> getPlatformUpdateCompleted;
        
        public event System.EventHandler<getPlatformUpdateInfoCompletedEventArgs> getPlatformUpdateInfoCompleted;
        
        public _1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateResult getPlatformUpdate(_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateRequest platformUpdateRequest) {
            return base.Channel.getPlatformUpdate(platformUpdateRequest);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetPlatformUpdate(_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateRequest platformUpdateRequest, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetPlatformUpdate(platformUpdateRequest, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public _1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateResult EndgetPlatformUpdate(System.IAsyncResult result) {
            return base.Channel.EndgetPlatformUpdate(result);
        }
        
        private System.IAsyncResult OnBegingetPlatformUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            _1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateRequest platformUpdateRequest = ((_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateRequest)(inValues[0]));
            return this.BegingetPlatformUpdate(platformUpdateRequest, callback, asyncState);
        }
        
        private object[] OnEndgetPlatformUpdate(System.IAsyncResult result) {
            _1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateResult retVal = this.EndgetPlatformUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetPlatformUpdateCompleted(object state) {
            if ((this.getPlatformUpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getPlatformUpdateCompleted(this, new getPlatformUpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getPlatformUpdateAsync(_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateRequest platformUpdateRequest) {
            this.getPlatformUpdateAsync(platformUpdateRequest, null);
        }
        
        public void getPlatformUpdateAsync(_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateRequest platformUpdateRequest, object userState) {
            if ((this.onBegingetPlatformUpdateDelegate == null)) {
                this.onBegingetPlatformUpdateDelegate = new BeginOperationDelegate(this.OnBegingetPlatformUpdate);
            }
            if ((this.onEndgetPlatformUpdateDelegate == null)) {
                this.onEndgetPlatformUpdateDelegate = new EndOperationDelegate(this.OnEndgetPlatformUpdate);
            }
            if ((this.ongetPlatformUpdateCompletedDelegate == null)) {
                this.ongetPlatformUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetPlatformUpdateCompleted);
            }
            base.InvokeAsync(this.onBegingetPlatformUpdateDelegate, new object[] {
                        platformUpdateRequest}, this.onEndgetPlatformUpdateDelegate, this.ongetPlatformUpdateCompletedDelegate, userState);
        }
        
        public _1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoResult getPlatformUpdateInfo(_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoRequest platformUpdateInfoRequest) {
            return base.Channel.getPlatformUpdateInfo(platformUpdateInfoRequest);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetPlatformUpdateInfo(_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoRequest platformUpdateInfoRequest, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetPlatformUpdateInfo(platformUpdateInfoRequest, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public _1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoResult EndgetPlatformUpdateInfo(System.IAsyncResult result) {
            return base.Channel.EndgetPlatformUpdateInfo(result);
        }
        
        private System.IAsyncResult OnBegingetPlatformUpdateInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            _1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoRequest platformUpdateInfoRequest = ((_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoRequest)(inValues[0]));
            return this.BegingetPlatformUpdateInfo(platformUpdateInfoRequest, callback, asyncState);
        }
        
        private object[] OnEndgetPlatformUpdateInfo(System.IAsyncResult result) {
            _1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoResult retVal = this.EndgetPlatformUpdateInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetPlatformUpdateInfoCompleted(object state) {
            if ((this.getPlatformUpdateInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getPlatformUpdateInfoCompleted(this, new getPlatformUpdateInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getPlatformUpdateInfoAsync(_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoRequest platformUpdateInfoRequest) {
            this.getPlatformUpdateInfoAsync(platformUpdateInfoRequest, null);
        }
        
        public void getPlatformUpdateInfoAsync(_1CUpdatesDownloader.UpdatePlatformReference.PlatformUpdateInfoRequest platformUpdateInfoRequest, object userState) {
            if ((this.onBegingetPlatformUpdateInfoDelegate == null)) {
                this.onBegingetPlatformUpdateInfoDelegate = new BeginOperationDelegate(this.OnBegingetPlatformUpdateInfo);
            }
            if ((this.onEndgetPlatformUpdateInfoDelegate == null)) {
                this.onEndgetPlatformUpdateInfoDelegate = new EndOperationDelegate(this.OnEndgetPlatformUpdateInfo);
            }
            if ((this.ongetPlatformUpdateInfoCompletedDelegate == null)) {
                this.ongetPlatformUpdateInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetPlatformUpdateInfoCompleted);
            }
            base.InvokeAsync(this.onBegingetPlatformUpdateInfoDelegate, new object[] {
                        platformUpdateInfoRequest}, this.onEndgetPlatformUpdateInfoDelegate, this.ongetPlatformUpdateInfoCompletedDelegate, userState);
        }
    }
}
