//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1CUpdatesDownloader.WebItsReference {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.webits.onec.ru")]
    public partial class InputParametersException : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.webits.onec.ru")]
    public partial class ProcessRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Parameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable=false)]
        public Parameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("parameters");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.webits.onec.ru")]
    public partial class Parameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> indexField;
        
        private string bpField;
        
        private string nameField;
        
        private string typeField;
        
        private string valueField;
        
        private Parameter[] parametersField;
        
        private Command[] commandsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
                this.RaisePropertyChanged("index");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string bp {
            get {
                return this.bpField;
            }
            set {
                this.bpField = value;
                this.RaisePropertyChanged("bp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable=false)]
        public Parameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("parameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("command", IsNullable=false)]
        public Command[] commands {
            get {
                return this.commandsField;
            }
            set {
                this.commandsField = value;
                this.RaisePropertyChanged("commands");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.webits.onec.ru")]
    public partial class Command : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private Parameter[] parametersField;
        
        private string variableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable=false)]
        public Parameter[] parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("parameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string variable {
            get {
                return this.variableField;
            }
            set {
                this.variableField = value;
                this.RaisePropertyChanged("variable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://ws.webits.onec.ru")]
    public partial class ProcessResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Command[] commandsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("command", IsNullable=false)]
        public Command[] commands {
            get {
                return this.commandsField;
            }
            set {
                this.commandsField = value;
                this.RaisePropertyChanged("commands");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ws.webits.onec.ru", ConfigurationName="WebItsReference.WebItsService")]
    public interface WebItsService {
        
        // CODEGEN: Generating message contract since the operation isConfigurationSupported is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _1CUpdatesDownloader.WebItsReference.isConfigurationSupportedResponse isConfigurationSupported(_1CUpdatesDownloader.WebItsReference.isConfigurationSupported request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginisConfigurationSupported(_1CUpdatesDownloader.WebItsReference.isConfigurationSupported request, System.AsyncCallback callback, object asyncState);
        
        _1CUpdatesDownloader.WebItsReference.isConfigurationSupportedResponse EndisConfigurationSupported(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since the operation sendmailtonet is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _1CUpdatesDownloader.WebItsReference.sendmailtonetResponse sendmailtonet(_1CUpdatesDownloader.WebItsReference.sendmailtonet request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Beginsendmailtonet(_1CUpdatesDownloader.WebItsReference.sendmailtonet request, System.AsyncCallback callback, object asyncState);
        
        _1CUpdatesDownloader.WebItsReference.sendmailtonetResponse Endsendmailtonet(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since the operation listbp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(_1CUpdatesDownloader.WebItsReference.InputParametersException), Action="", Name="InputParametersException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _1CUpdatesDownloader.WebItsReference.listbpResponse listbp(_1CUpdatesDownloader.WebItsReference.listbp request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Beginlistbp(_1CUpdatesDownloader.WebItsReference.listbp request, System.AsyncCallback callback, object asyncState);
        
        _1CUpdatesDownloader.WebItsReference.listbpResponse Endlistbp(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since the operation test is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _1CUpdatesDownloader.WebItsReference.testResponse test(_1CUpdatesDownloader.WebItsReference.test request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Begintest(_1CUpdatesDownloader.WebItsReference.test request, System.AsyncCallback callback, object asyncState);
        
        _1CUpdatesDownloader.WebItsReference.testResponse Endtest(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since the operation process is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(_1CUpdatesDownloader.WebItsReference.InputParametersException), Action="", Name="InputParametersException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _1CUpdatesDownloader.WebItsReference.processResponse process(_1CUpdatesDownloader.WebItsReference.process request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Beginprocess(_1CUpdatesDownloader.WebItsReference.process request, System.AsyncCallback callback, object asyncState);
        
        _1CUpdatesDownloader.WebItsReference.processResponse Endprocess(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since the operation isHaveIts is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _1CUpdatesDownloader.WebItsReference.isHaveItsResponse isHaveIts(_1CUpdatesDownloader.WebItsReference.isHaveIts request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginisHaveIts(_1CUpdatesDownloader.WebItsReference.isHaveIts request, System.AsyncCallback callback, object asyncState);
        
        _1CUpdatesDownloader.WebItsReference.isHaveItsResponse EndisHaveIts(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since the operation isReady is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        _1CUpdatesDownloader.WebItsReference.isReadyResponse isReady(_1CUpdatesDownloader.WebItsReference.isReady request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BeginisReady(_1CUpdatesDownloader.WebItsReference.isReady request, System.AsyncCallback callback, object asyncState);
        
        _1CUpdatesDownloader.WebItsReference.isReadyResponse EndisReady(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isConfigurationSupported {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isConfigurationSupported", Namespace="https://ws.webits.onec.ru", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isConfigurationSupported1;
        
        public isConfigurationSupported() {
        }
        
        public isConfigurationSupported(string isConfigurationSupported1) {
            this.isConfigurationSupported1 = isConfigurationSupported1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isConfigurationSupportedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isConfigurationSupportedResponse", Namespace="https://ws.webits.onec.ru", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> isConfigurationSupportedResponse1;
        
        public isConfigurationSupportedResponse() {
        }
        
        public isConfigurationSupportedResponse(System.Nullable<bool> isConfigurationSupportedResponse1) {
            this.isConfigurationSupportedResponse1 = isConfigurationSupportedResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendmailtonet {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws.webits.onec.ru", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable=false)]
        public _1CUpdatesDownloader.WebItsReference.Parameter[] sendmailParams;
        
        public sendmailtonet() {
        }
        
        public sendmailtonet(_1CUpdatesDownloader.WebItsReference.Parameter[] sendmailParams) {
            this.sendmailParams = sendmailParams;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendmailtonetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws.webits.onec.ru", Order=0)]
        public _1CUpdatesDownloader.WebItsReference.ProcessResponseType processResponse;
        
        public sendmailtonetResponse() {
        }
        
        public sendmailtonetResponse(_1CUpdatesDownloader.WebItsReference.ProcessResponseType processResponse) {
            this.processResponse = processResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listbp {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listbp", Namespace="https://ws.webits.onec.ru", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public _1CUpdatesDownloader.WebItsReference.ProcessRequestType listbp1;
        
        public listbp() {
        }
        
        public listbp(_1CUpdatesDownloader.WebItsReference.ProcessRequestType listbp1) {
            this.listbp1 = listbp1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listbpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws.webits.onec.ru", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public _1CUpdatesDownloader.WebItsReference.ProcessRequestType listbp;
        
        public listbpResponse() {
        }
        
        public listbpResponse(_1CUpdatesDownloader.WebItsReference.ProcessRequestType listbp) {
            this.listbp = listbp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class test {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws.webits.onec.ru", Order=0)]
        public string testRequest;
        
        public test() {
        }
        
        public test(string testRequest) {
            this.testRequest = testRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="testResponse", Namespace="https://ws.webits.onec.ru", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("parameter", IsNullable=false)]
        public _1CUpdatesDownloader.WebItsReference.Parameter[] testResponse1;
        
        public testResponse() {
        }
        
        public testResponse(_1CUpdatesDownloader.WebItsReference.Parameter[] testResponse1) {
            this.testResponse1 = testResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class process {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws.webits.onec.ru", Order=0)]
        public _1CUpdatesDownloader.WebItsReference.ProcessRequestType processRequest;
        
        public process() {
        }
        
        public process(_1CUpdatesDownloader.WebItsReference.ProcessRequestType processRequest) {
            this.processRequest = processRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processResponse", Namespace="https://ws.webits.onec.ru", Order=0)]
        public _1CUpdatesDownloader.WebItsReference.ProcessResponseType processResponse1;
        
        public processResponse() {
        }
        
        public processResponse(_1CUpdatesDownloader.WebItsReference.ProcessResponseType processResponse1) {
            this.processResponse1 = processResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isHaveIts {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isHaveIts", Namespace="https://ws.webits.onec.ru", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isHaveIts1;
        
        public isHaveIts() {
        }
        
        public isHaveIts(string isHaveIts1) {
            this.isHaveIts1 = isHaveIts1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isHaveItsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://ws.webits.onec.ru", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isHaveIts;
        
        public isHaveItsResponse() {
        }
        
        public isHaveItsResponse(string isHaveIts) {
            this.isHaveIts = isHaveIts;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isReady {
        
        public isReady() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isReadyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isReadyResponse", Namespace="https://ws.webits.onec.ru", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string isReadyResponse1;
        
        public isReadyResponse() {
        }
        
        public isReadyResponse(string isReadyResponse1) {
            this.isReadyResponse1 = isReadyResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebItsServiceChannel : _1CUpdatesDownloader.WebItsReference.WebItsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class isConfigurationSupportedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public isConfigurationSupportedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Nullable<bool> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Nullable<bool>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sendmailtonetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public sendmailtonetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public _1CUpdatesDownloader.WebItsReference.ProcessResponseType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((_1CUpdatesDownloader.WebItsReference.ProcessResponseType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class listbpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public listbpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public _1CUpdatesDownloader.WebItsReference.ProcessRequestType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((_1CUpdatesDownloader.WebItsReference.ProcessRequestType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class testCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public testCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public _1CUpdatesDownloader.WebItsReference.Parameter[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((_1CUpdatesDownloader.WebItsReference.Parameter[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class processCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public processCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public _1CUpdatesDownloader.WebItsReference.ProcessResponseType Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((_1CUpdatesDownloader.WebItsReference.ProcessResponseType)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class isHaveItsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public isHaveItsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class isReadyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public isReadyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebItsServiceClient : System.ServiceModel.ClientBase<_1CUpdatesDownloader.WebItsReference.WebItsService>, _1CUpdatesDownloader.WebItsReference.WebItsService {
        
        private BeginOperationDelegate onBeginisConfigurationSupportedDelegate;
        
        private EndOperationDelegate onEndisConfigurationSupportedDelegate;
        
        private System.Threading.SendOrPostCallback onisConfigurationSupportedCompletedDelegate;
        
        private BeginOperationDelegate onBeginsendmailtonetDelegate;
        
        private EndOperationDelegate onEndsendmailtonetDelegate;
        
        private System.Threading.SendOrPostCallback onsendmailtonetCompletedDelegate;
        
        private BeginOperationDelegate onBeginlistbpDelegate;
        
        private EndOperationDelegate onEndlistbpDelegate;
        
        private System.Threading.SendOrPostCallback onlistbpCompletedDelegate;
        
        private BeginOperationDelegate onBegintestDelegate;
        
        private EndOperationDelegate onEndtestDelegate;
        
        private System.Threading.SendOrPostCallback ontestCompletedDelegate;
        
        private BeginOperationDelegate onBeginprocessDelegate;
        
        private EndOperationDelegate onEndprocessDelegate;
        
        private System.Threading.SendOrPostCallback onprocessCompletedDelegate;
        
        private BeginOperationDelegate onBeginisHaveItsDelegate;
        
        private EndOperationDelegate onEndisHaveItsDelegate;
        
        private System.Threading.SendOrPostCallback onisHaveItsCompletedDelegate;
        
        private BeginOperationDelegate onBeginisReadyDelegate;
        
        private EndOperationDelegate onEndisReadyDelegate;
        
        private System.Threading.SendOrPostCallback onisReadyCompletedDelegate;
        
        public WebItsServiceClient() {
        }
        
        public WebItsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebItsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebItsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebItsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<isConfigurationSupportedCompletedEventArgs> isConfigurationSupportedCompleted;
        
        public event System.EventHandler<sendmailtonetCompletedEventArgs> sendmailtonetCompleted;
        
        public event System.EventHandler<listbpCompletedEventArgs> listbpCompleted;
        
        public event System.EventHandler<testCompletedEventArgs> testCompleted;
        
        public event System.EventHandler<processCompletedEventArgs> processCompleted;
        
        public event System.EventHandler<isHaveItsCompletedEventArgs> isHaveItsCompleted;
        
        public event System.EventHandler<isReadyCompletedEventArgs> isReadyCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1CUpdatesDownloader.WebItsReference.isConfigurationSupportedResponse _1CUpdatesDownloader.WebItsReference.WebItsService.isConfigurationSupported(_1CUpdatesDownloader.WebItsReference.isConfigurationSupported request) {
            return base.Channel.isConfigurationSupported(request);
        }
        
        public System.Nullable<bool> isConfigurationSupported(string isConfigurationSupported1) {
            _1CUpdatesDownloader.WebItsReference.isConfigurationSupported inValue = new _1CUpdatesDownloader.WebItsReference.isConfigurationSupported();
            inValue.isConfigurationSupported1 = isConfigurationSupported1;
            _1CUpdatesDownloader.WebItsReference.isConfigurationSupportedResponse retVal = ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).isConfigurationSupported(inValue);
            return retVal.isConfigurationSupportedResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult _1CUpdatesDownloader.WebItsReference.WebItsService.BeginisConfigurationSupported(_1CUpdatesDownloader.WebItsReference.isConfigurationSupported request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginisConfigurationSupported(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginisConfigurationSupported(string isConfigurationSupported1, System.AsyncCallback callback, object asyncState) {
            _1CUpdatesDownloader.WebItsReference.isConfigurationSupported inValue = new _1CUpdatesDownloader.WebItsReference.isConfigurationSupported();
            inValue.isConfigurationSupported1 = isConfigurationSupported1;
            return ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).BeginisConfigurationSupported(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1CUpdatesDownloader.WebItsReference.isConfigurationSupportedResponse _1CUpdatesDownloader.WebItsReference.WebItsService.EndisConfigurationSupported(System.IAsyncResult result) {
            return base.Channel.EndisConfigurationSupported(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Nullable<bool> EndisConfigurationSupported(System.IAsyncResult result) {
            _1CUpdatesDownloader.WebItsReference.isConfigurationSupportedResponse retVal = ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).EndisConfigurationSupported(result);
            return retVal.isConfigurationSupportedResponse1;
        }
        
        private System.IAsyncResult OnBeginisConfigurationSupported(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string isConfigurationSupported1 = ((string)(inValues[0]));
            return this.BeginisConfigurationSupported(isConfigurationSupported1, callback, asyncState);
        }
        
        private object[] OnEndisConfigurationSupported(System.IAsyncResult result) {
            System.Nullable<bool> retVal = this.EndisConfigurationSupported(result);
            return new object[] {
                    retVal};
        }
        
        private void OnisConfigurationSupportedCompleted(object state) {
            if ((this.isConfigurationSupportedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.isConfigurationSupportedCompleted(this, new isConfigurationSupportedCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void isConfigurationSupportedAsync(string isConfigurationSupported1) {
            this.isConfigurationSupportedAsync(isConfigurationSupported1, null);
        }
        
        public void isConfigurationSupportedAsync(string isConfigurationSupported1, object userState) {
            if ((this.onBeginisConfigurationSupportedDelegate == null)) {
                this.onBeginisConfigurationSupportedDelegate = new BeginOperationDelegate(this.OnBeginisConfigurationSupported);
            }
            if ((this.onEndisConfigurationSupportedDelegate == null)) {
                this.onEndisConfigurationSupportedDelegate = new EndOperationDelegate(this.OnEndisConfigurationSupported);
            }
            if ((this.onisConfigurationSupportedCompletedDelegate == null)) {
                this.onisConfigurationSupportedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnisConfigurationSupportedCompleted);
            }
            base.InvokeAsync(this.onBeginisConfigurationSupportedDelegate, new object[] {
                        isConfigurationSupported1}, this.onEndisConfigurationSupportedDelegate, this.onisConfigurationSupportedCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1CUpdatesDownloader.WebItsReference.sendmailtonetResponse _1CUpdatesDownloader.WebItsReference.WebItsService.sendmailtonet(_1CUpdatesDownloader.WebItsReference.sendmailtonet request) {
            return base.Channel.sendmailtonet(request);
        }
        
        public _1CUpdatesDownloader.WebItsReference.ProcessResponseType sendmailtonet(_1CUpdatesDownloader.WebItsReference.Parameter[] sendmailParams) {
            _1CUpdatesDownloader.WebItsReference.sendmailtonet inValue = new _1CUpdatesDownloader.WebItsReference.sendmailtonet();
            inValue.sendmailParams = sendmailParams;
            _1CUpdatesDownloader.WebItsReference.sendmailtonetResponse retVal = ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).sendmailtonet(inValue);
            return retVal.processResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult _1CUpdatesDownloader.WebItsReference.WebItsService.Beginsendmailtonet(_1CUpdatesDownloader.WebItsReference.sendmailtonet request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginsendmailtonet(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginsendmailtonet(_1CUpdatesDownloader.WebItsReference.Parameter[] sendmailParams, System.AsyncCallback callback, object asyncState) {
            _1CUpdatesDownloader.WebItsReference.sendmailtonet inValue = new _1CUpdatesDownloader.WebItsReference.sendmailtonet();
            inValue.sendmailParams = sendmailParams;
            return ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).Beginsendmailtonet(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1CUpdatesDownloader.WebItsReference.sendmailtonetResponse _1CUpdatesDownloader.WebItsReference.WebItsService.Endsendmailtonet(System.IAsyncResult result) {
            return base.Channel.Endsendmailtonet(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public _1CUpdatesDownloader.WebItsReference.ProcessResponseType Endsendmailtonet(System.IAsyncResult result) {
            _1CUpdatesDownloader.WebItsReference.sendmailtonetResponse retVal = ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).Endsendmailtonet(result);
            return retVal.processResponse;
        }
        
        private System.IAsyncResult OnBeginsendmailtonet(object[] inValues, System.AsyncCallback callback, object asyncState) {
            _1CUpdatesDownloader.WebItsReference.Parameter[] sendmailParams = ((_1CUpdatesDownloader.WebItsReference.Parameter[])(inValues[0]));
            return this.Beginsendmailtonet(sendmailParams, callback, asyncState);
        }
        
        private object[] OnEndsendmailtonet(System.IAsyncResult result) {
            _1CUpdatesDownloader.WebItsReference.ProcessResponseType retVal = this.Endsendmailtonet(result);
            return new object[] {
                    retVal};
        }
        
        private void OnsendmailtonetCompleted(object state) {
            if ((this.sendmailtonetCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.sendmailtonetCompleted(this, new sendmailtonetCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void sendmailtonetAsync(_1CUpdatesDownloader.WebItsReference.Parameter[] sendmailParams) {
            this.sendmailtonetAsync(sendmailParams, null);
        }
        
        public void sendmailtonetAsync(_1CUpdatesDownloader.WebItsReference.Parameter[] sendmailParams, object userState) {
            if ((this.onBeginsendmailtonetDelegate == null)) {
                this.onBeginsendmailtonetDelegate = new BeginOperationDelegate(this.OnBeginsendmailtonet);
            }
            if ((this.onEndsendmailtonetDelegate == null)) {
                this.onEndsendmailtonetDelegate = new EndOperationDelegate(this.OnEndsendmailtonet);
            }
            if ((this.onsendmailtonetCompletedDelegate == null)) {
                this.onsendmailtonetCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnsendmailtonetCompleted);
            }
            base.InvokeAsync(this.onBeginsendmailtonetDelegate, new object[] {
                        sendmailParams}, this.onEndsendmailtonetDelegate, this.onsendmailtonetCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1CUpdatesDownloader.WebItsReference.listbpResponse _1CUpdatesDownloader.WebItsReference.WebItsService.listbp(_1CUpdatesDownloader.WebItsReference.listbp request) {
            return base.Channel.listbp(request);
        }
        
        public _1CUpdatesDownloader.WebItsReference.ProcessRequestType listbp(_1CUpdatesDownloader.WebItsReference.ProcessRequestType listbp1) {
            _1CUpdatesDownloader.WebItsReference.listbp inValue = new _1CUpdatesDownloader.WebItsReference.listbp();
            inValue.listbp1 = listbp1;
            _1CUpdatesDownloader.WebItsReference.listbpResponse retVal = ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).listbp(inValue);
            return retVal.listbp;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult _1CUpdatesDownloader.WebItsReference.WebItsService.Beginlistbp(_1CUpdatesDownloader.WebItsReference.listbp request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginlistbp(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginlistbp(_1CUpdatesDownloader.WebItsReference.ProcessRequestType listbp1, System.AsyncCallback callback, object asyncState) {
            _1CUpdatesDownloader.WebItsReference.listbp inValue = new _1CUpdatesDownloader.WebItsReference.listbp();
            inValue.listbp1 = listbp1;
            return ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).Beginlistbp(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1CUpdatesDownloader.WebItsReference.listbpResponse _1CUpdatesDownloader.WebItsReference.WebItsService.Endlistbp(System.IAsyncResult result) {
            return base.Channel.Endlistbp(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public _1CUpdatesDownloader.WebItsReference.ProcessRequestType Endlistbp(System.IAsyncResult result) {
            _1CUpdatesDownloader.WebItsReference.listbpResponse retVal = ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).Endlistbp(result);
            return retVal.listbp;
        }
        
        private System.IAsyncResult OnBeginlistbp(object[] inValues, System.AsyncCallback callback, object asyncState) {
            _1CUpdatesDownloader.WebItsReference.ProcessRequestType listbp1 = ((_1CUpdatesDownloader.WebItsReference.ProcessRequestType)(inValues[0]));
            return this.Beginlistbp(listbp1, callback, asyncState);
        }
        
        private object[] OnEndlistbp(System.IAsyncResult result) {
            _1CUpdatesDownloader.WebItsReference.ProcessRequestType retVal = this.Endlistbp(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlistbpCompleted(object state) {
            if ((this.listbpCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.listbpCompleted(this, new listbpCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void listbpAsync(_1CUpdatesDownloader.WebItsReference.ProcessRequestType listbp1) {
            this.listbpAsync(listbp1, null);
        }
        
        public void listbpAsync(_1CUpdatesDownloader.WebItsReference.ProcessRequestType listbp1, object userState) {
            if ((this.onBeginlistbpDelegate == null)) {
                this.onBeginlistbpDelegate = new BeginOperationDelegate(this.OnBeginlistbp);
            }
            if ((this.onEndlistbpDelegate == null)) {
                this.onEndlistbpDelegate = new EndOperationDelegate(this.OnEndlistbp);
            }
            if ((this.onlistbpCompletedDelegate == null)) {
                this.onlistbpCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlistbpCompleted);
            }
            base.InvokeAsync(this.onBeginlistbpDelegate, new object[] {
                        listbp1}, this.onEndlistbpDelegate, this.onlistbpCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1CUpdatesDownloader.WebItsReference.testResponse _1CUpdatesDownloader.WebItsReference.WebItsService.test(_1CUpdatesDownloader.WebItsReference.test request) {
            return base.Channel.test(request);
        }
        
        public _1CUpdatesDownloader.WebItsReference.Parameter[] test(string testRequest) {
            _1CUpdatesDownloader.WebItsReference.test inValue = new _1CUpdatesDownloader.WebItsReference.test();
            inValue.testRequest = testRequest;
            _1CUpdatesDownloader.WebItsReference.testResponse retVal = ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).test(inValue);
            return retVal.testResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult _1CUpdatesDownloader.WebItsReference.WebItsService.Begintest(_1CUpdatesDownloader.WebItsReference.test request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Begintest(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Begintest(string testRequest, System.AsyncCallback callback, object asyncState) {
            _1CUpdatesDownloader.WebItsReference.test inValue = new _1CUpdatesDownloader.WebItsReference.test();
            inValue.testRequest = testRequest;
            return ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).Begintest(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1CUpdatesDownloader.WebItsReference.testResponse _1CUpdatesDownloader.WebItsReference.WebItsService.Endtest(System.IAsyncResult result) {
            return base.Channel.Endtest(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public _1CUpdatesDownloader.WebItsReference.Parameter[] Endtest(System.IAsyncResult result) {
            _1CUpdatesDownloader.WebItsReference.testResponse retVal = ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).Endtest(result);
            return retVal.testResponse1;
        }
        
        private System.IAsyncResult OnBegintest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string testRequest = ((string)(inValues[0]));
            return this.Begintest(testRequest, callback, asyncState);
        }
        
        private object[] OnEndtest(System.IAsyncResult result) {
            _1CUpdatesDownloader.WebItsReference.Parameter[] retVal = this.Endtest(result);
            return new object[] {
                    retVal};
        }
        
        private void OntestCompleted(object state) {
            if ((this.testCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.testCompleted(this, new testCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void testAsync(string testRequest) {
            this.testAsync(testRequest, null);
        }
        
        public void testAsync(string testRequest, object userState) {
            if ((this.onBegintestDelegate == null)) {
                this.onBegintestDelegate = new BeginOperationDelegate(this.OnBegintest);
            }
            if ((this.onEndtestDelegate == null)) {
                this.onEndtestDelegate = new EndOperationDelegate(this.OnEndtest);
            }
            if ((this.ontestCompletedDelegate == null)) {
                this.ontestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OntestCompleted);
            }
            base.InvokeAsync(this.onBegintestDelegate, new object[] {
                        testRequest}, this.onEndtestDelegate, this.ontestCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1CUpdatesDownloader.WebItsReference.processResponse _1CUpdatesDownloader.WebItsReference.WebItsService.process(_1CUpdatesDownloader.WebItsReference.process request) {
            return base.Channel.process(request);
        }
        
        public _1CUpdatesDownloader.WebItsReference.ProcessResponseType process(_1CUpdatesDownloader.WebItsReference.ProcessRequestType processRequest) {
            _1CUpdatesDownloader.WebItsReference.process inValue = new _1CUpdatesDownloader.WebItsReference.process();
            inValue.processRequest = processRequest;
            _1CUpdatesDownloader.WebItsReference.processResponse retVal = ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).process(inValue);
            return retVal.processResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult _1CUpdatesDownloader.WebItsReference.WebItsService.Beginprocess(_1CUpdatesDownloader.WebItsReference.process request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginprocess(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginprocess(_1CUpdatesDownloader.WebItsReference.ProcessRequestType processRequest, System.AsyncCallback callback, object asyncState) {
            _1CUpdatesDownloader.WebItsReference.process inValue = new _1CUpdatesDownloader.WebItsReference.process();
            inValue.processRequest = processRequest;
            return ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).Beginprocess(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1CUpdatesDownloader.WebItsReference.processResponse _1CUpdatesDownloader.WebItsReference.WebItsService.Endprocess(System.IAsyncResult result) {
            return base.Channel.Endprocess(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public _1CUpdatesDownloader.WebItsReference.ProcessResponseType Endprocess(System.IAsyncResult result) {
            _1CUpdatesDownloader.WebItsReference.processResponse retVal = ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).Endprocess(result);
            return retVal.processResponse1;
        }
        
        private System.IAsyncResult OnBeginprocess(object[] inValues, System.AsyncCallback callback, object asyncState) {
            _1CUpdatesDownloader.WebItsReference.ProcessRequestType processRequest = ((_1CUpdatesDownloader.WebItsReference.ProcessRequestType)(inValues[0]));
            return this.Beginprocess(processRequest, callback, asyncState);
        }
        
        private object[] OnEndprocess(System.IAsyncResult result) {
            _1CUpdatesDownloader.WebItsReference.ProcessResponseType retVal = this.Endprocess(result);
            return new object[] {
                    retVal};
        }
        
        private void OnprocessCompleted(object state) {
            if ((this.processCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.processCompleted(this, new processCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void processAsync(_1CUpdatesDownloader.WebItsReference.ProcessRequestType processRequest) {
            this.processAsync(processRequest, null);
        }
        
        public void processAsync(_1CUpdatesDownloader.WebItsReference.ProcessRequestType processRequest, object userState) {
            if ((this.onBeginprocessDelegate == null)) {
                this.onBeginprocessDelegate = new BeginOperationDelegate(this.OnBeginprocess);
            }
            if ((this.onEndprocessDelegate == null)) {
                this.onEndprocessDelegate = new EndOperationDelegate(this.OnEndprocess);
            }
            if ((this.onprocessCompletedDelegate == null)) {
                this.onprocessCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnprocessCompleted);
            }
            base.InvokeAsync(this.onBeginprocessDelegate, new object[] {
                        processRequest}, this.onEndprocessDelegate, this.onprocessCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1CUpdatesDownloader.WebItsReference.isHaveItsResponse _1CUpdatesDownloader.WebItsReference.WebItsService.isHaveIts(_1CUpdatesDownloader.WebItsReference.isHaveIts request) {
            return base.Channel.isHaveIts(request);
        }
        
        public string isHaveIts(string isHaveIts1) {
            _1CUpdatesDownloader.WebItsReference.isHaveIts inValue = new _1CUpdatesDownloader.WebItsReference.isHaveIts();
            inValue.isHaveIts1 = isHaveIts1;
            _1CUpdatesDownloader.WebItsReference.isHaveItsResponse retVal = ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).isHaveIts(inValue);
            return retVal.isHaveIts;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult _1CUpdatesDownloader.WebItsReference.WebItsService.BeginisHaveIts(_1CUpdatesDownloader.WebItsReference.isHaveIts request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginisHaveIts(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginisHaveIts(string isHaveIts1, System.AsyncCallback callback, object asyncState) {
            _1CUpdatesDownloader.WebItsReference.isHaveIts inValue = new _1CUpdatesDownloader.WebItsReference.isHaveIts();
            inValue.isHaveIts1 = isHaveIts1;
            return ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).BeginisHaveIts(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1CUpdatesDownloader.WebItsReference.isHaveItsResponse _1CUpdatesDownloader.WebItsReference.WebItsService.EndisHaveIts(System.IAsyncResult result) {
            return base.Channel.EndisHaveIts(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndisHaveIts(System.IAsyncResult result) {
            _1CUpdatesDownloader.WebItsReference.isHaveItsResponse retVal = ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).EndisHaveIts(result);
            return retVal.isHaveIts;
        }
        
        private System.IAsyncResult OnBeginisHaveIts(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string isHaveIts1 = ((string)(inValues[0]));
            return this.BeginisHaveIts(isHaveIts1, callback, asyncState);
        }
        
        private object[] OnEndisHaveIts(System.IAsyncResult result) {
            string retVal = this.EndisHaveIts(result);
            return new object[] {
                    retVal};
        }
        
        private void OnisHaveItsCompleted(object state) {
            if ((this.isHaveItsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.isHaveItsCompleted(this, new isHaveItsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void isHaveItsAsync(string isHaveIts1) {
            this.isHaveItsAsync(isHaveIts1, null);
        }
        
        public void isHaveItsAsync(string isHaveIts1, object userState) {
            if ((this.onBeginisHaveItsDelegate == null)) {
                this.onBeginisHaveItsDelegate = new BeginOperationDelegate(this.OnBeginisHaveIts);
            }
            if ((this.onEndisHaveItsDelegate == null)) {
                this.onEndisHaveItsDelegate = new EndOperationDelegate(this.OnEndisHaveIts);
            }
            if ((this.onisHaveItsCompletedDelegate == null)) {
                this.onisHaveItsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnisHaveItsCompleted);
            }
            base.InvokeAsync(this.onBeginisHaveItsDelegate, new object[] {
                        isHaveIts1}, this.onEndisHaveItsDelegate, this.onisHaveItsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1CUpdatesDownloader.WebItsReference.isReadyResponse _1CUpdatesDownloader.WebItsReference.WebItsService.isReady(_1CUpdatesDownloader.WebItsReference.isReady request) {
            return base.Channel.isReady(request);
        }
        
        public string isReady() {
            _1CUpdatesDownloader.WebItsReference.isReady inValue = new _1CUpdatesDownloader.WebItsReference.isReady();
            _1CUpdatesDownloader.WebItsReference.isReadyResponse retVal = ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).isReady(inValue);
            return retVal.isReadyResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult _1CUpdatesDownloader.WebItsReference.WebItsService.BeginisReady(_1CUpdatesDownloader.WebItsReference.isReady request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginisReady(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginisReady(System.AsyncCallback callback, object asyncState) {
            _1CUpdatesDownloader.WebItsReference.isReady inValue = new _1CUpdatesDownloader.WebItsReference.isReady();
            return ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).BeginisReady(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _1CUpdatesDownloader.WebItsReference.isReadyResponse _1CUpdatesDownloader.WebItsReference.WebItsService.EndisReady(System.IAsyncResult result) {
            return base.Channel.EndisReady(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public string EndisReady(System.IAsyncResult result) {
            _1CUpdatesDownloader.WebItsReference.isReadyResponse retVal = ((_1CUpdatesDownloader.WebItsReference.WebItsService)(this)).EndisReady(result);
            return retVal.isReadyResponse1;
        }
        
        private System.IAsyncResult OnBeginisReady(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginisReady(callback, asyncState);
        }
        
        private object[] OnEndisReady(System.IAsyncResult result) {
            string retVal = this.EndisReady(result);
            return new object[] {
                    retVal};
        }
        
        private void OnisReadyCompleted(object state) {
            if ((this.isReadyCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.isReadyCompleted(this, new isReadyCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void isReadyAsync() {
            this.isReadyAsync(null);
        }
        
        public void isReadyAsync(object userState) {
            if ((this.onBeginisReadyDelegate == null)) {
                this.onBeginisReadyDelegate = new BeginOperationDelegate(this.OnBeginisReady);
            }
            if ((this.onEndisReadyDelegate == null)) {
                this.onEndisReadyDelegate = new EndOperationDelegate(this.OnEndisReady);
            }
            if ((this.onisReadyCompletedDelegate == null)) {
                this.onisReadyCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnisReadyCompleted);
            }
            base.InvokeAsync(this.onBeginisReadyDelegate, null, this.onEndisReadyDelegate, this.onisReadyCompletedDelegate, userState);
        }
    }
}
